### ISSUE TITLE
Queue multiple notifications rather than displaying them simultaneously.

### ISSUE THREAD

**Issue by camclendenin** [kunass2/BSForegroundNotification#10]
On screen notifications should be limited to 1 at a time. Currently they just pile on top of each other which is not ideal. Instead, notifications should be added to a queue, which would be responsible for presenting the next notification from the queue once the previous one has been dismissed. Doing this fixes:
- Notifications piling up and becoming hard to read because of view transparency.
- User being interrupted from his interaction with the first notification.
- `UIStatusBar` hide/unhiding bug. Currently once the first notification disappears, the status bar is unhidden.... even if a new notification is already on screen.
- Inconsistency from the way Apple displays push notifications (they use a queue).

**Comment by kunass2** [comment]
Ok, I will apply your suggestions next week:-) thanks for your reply. Maybe you would like to improve library and create pull request? Then I immediately push it to cocoapods.

**Comment by camclendenin** [comment]
Yep @kunass2 I might be able to help out on this issue next week.

**Comment by MHX792** [comment]
Any progress on this one?

**Comment by kunass2** [comment]
I will care about this soon. Let you know.

---
Bartłomiej Semańczyk

**Comment by kunass2** [comment]
@MHX792 @camclendenin I released a new version with queued notifications. Another one will appear once after the previous one is dismissed.
