### ISSUE TITLE
Trigger Action

### ISSUE THREAD

**Issue by bungkhus** [kunass2/BSForegroundNotification#11]
How can i trigger when user tab the notification, and the button action?

**Comment by kunass2** [comment]
It is nit an issue. Just read the Usage part.

**Comment by bungkhus** [comment]
but I can not find it

**Comment by kunass2** [comment]
https://github.com/kunass2/BSForegroundNotification/blob/master/README.md

**Comment by bungkhus** [comment]
so, where i put this code?
@objc public protocol BSForegroundNotificationDelegate: class, UIApplicationDelegate {  
    optional func foregroundRemoteNotificationWasTouched(userInfo: [NSObject: AnyObject])
    optional func foregroundLocalNotificationWasTouched(localNotifcation: UILocalNotification)
}

**Comment by kunass2** [comment]
nowhere, you just need to set your class as delegate of notification and conform your class to above protocol.
