### ISSUE TITLE
can not handle localpushnotification

### ISSUE THREAD

**Issue by bungkhus** [kunass2/BSForegroundNotification#12]
I have tried to use local **BSForegroundNotification** to get local push notification. But when I touched the notification, no reaction. I use this code:
_

> func application (application: UIApplication, handleActionWithIdentifier identifier: String ?, forLocalNotification notification: UILocalNotification, completionHandler: () -> Void)

_
in my AppDelegate, but it still did not happen anything.
What should I do?
Thanks.

**Comment by kunass2** [comment]
Please read more about delegates in ios. You need to set delegate for your notification. Before you present it.
