### ISSUE TITLE
timeToDismissNotification no longer avalible

### ISSUE THREAD

**Issue by H2wk** [kunass2/BSForegroundNotification#14]
No longer able to use present notification with time for display in version 1.9.1

![screen shot 2016-10-24 at 17 06 04](https://cloud.githubusercontent.com/assets/3350219/19653426/6a024182-9a0c-11e6-86d7-0ccd0822e726.png)

Can you please fix this.

**Comment by kunass2** [comment]
It is not a bug. Currently this is a static property of `BSForegroundNotification`:

usage:

```
BSForegroundNotification.timeToDismissNotification = 5
```

setup it once in your `AppDelegate`.

**Comment by H2wk** [comment]
A great. Thank you.
