### ISSUE TITLE
Can't open Firebase push notification

### ISSUE THREAD

**Issue by ghost** [kunass2/BSForegroundNotification#15]
Hi there.

I am struggling with displaying push notifications sent from my Firebase console in my app. It obviously shows when my phone screen is locked, but I can't seem to get this working. I honestly have to say that I am also a bit confused, and I would really appreciate if any could help me with this.

This is some of my code in appDelegate.swift:

```
    func application(_ application: UIApplication, didReceiveRemoteNotification userInfo: [AnyHashable : Any], fetchCompletionHandler completionHandler: @escaping (UIBackgroundFetchResult) -> Void) {

        let token = FIRInstanceID.instanceID().token()
        FIRMessaging.messaging().appDidReceiveMessage(userInfo)

        print(token)
        print("MessageID : \(userInfo["gcm_message_id"])")
        print(userInfo)


    }
```

It's in here I have put the code for the foreground push notification as well. So it looks like this:

```
    func application(_ application: UIApplication, didReceiveRemoteNotification userInfo: [AnyHashable : Any], fetchCompletionHandler completionHandler: @escaping (UIBackgroundFetchResult) -> Void) {

        let token = FIRInstanceID.instanceID().token()
        FIRMessaging.messaging().appDidReceiveMessage(userInfo)

        print(token)
        print("MessageID : \(userInfo["gcm_message_id"])")
        print(userInfo)

         let notification = BSForegroundNotification(userInfo: userInfo)

        BSForegroundNotification.systemSoundID = 1004
        notification.delegate = self
        notification.presentNotification()
    }
```

However, this does not seem to work. Any ideas on how I would solve this?

**Comment by kunass2** [comment]
Everything seems to be fine in your code. Are you sure that your app delegate method is called? Could you send me your userInfo example here? Why do you think that it doesnt work? What exactly doesnt work?

**Comment by ghost** [comment]
I will get back to you very shortly, I troubleshooted an error regarding the Firebase Cloud Messaging-system, which suddenly stopped working for me. Once this is fixed, I'll update here.

**Comment by ghost** [comment]
Hi there! Sorry for being late. I just discovered after releasing the app, that the notification doesn't seem to show on iOS 10, however - it does on my friends iOS 9 devices. Is this an issue you are aware of? Will there be a fix for this soon? Regardless of that, the notifications seems to work flawless!

**Comment by kunass2** [comment]
No, it is not the bug related to `BSForegroundNotification` framework. Using iOS 10, the way how notifications are handled was changed a bit. This is not related to the framework. Please be aware of that.

**Comment by ghost** [comment]
Oh, I see - I am truly sorry, then. Could you point me in the right direction, on how I would approach this issue?

**Comment by kunass2** [comment]
See [this](http://stackoverflow.com/questions/39532953/push-notifications-not-being-received-on-ios-10-but-working-on-ios-9-and-before) question on stackoverflow.com
