### ISSUE TITLE
It seems like long subtitle text stays one line unless you call presentView()?

### ISSUE THREAD

**Issue by dilizarov** [kunass2/BSForegroundNotification#5]
I tested out a long notification and the subtitle text for some reason stayed 1 line. When I finally pulled down, it showed all the text. I tried calling the presentView function in presentNotification and that fixed the problem, but I'm not sure why this is happening.

**Comment by kunass2** [comment]
It is not an issue. It works as it is supposed to be working. Subtitle NEVER will be presented fully unless you pull it down. It is like apple's notification works. I close that issue.
