### ISSUE TITLE
Increase the size of the "send" button for TextInput actions

### ISSUE THREAD

**Issue by camclendenin** [kunass2/BSForegroundNotification#9]
**Problem**
When attempting to "send" user inputted text for a notification uses `.TextInput` actions, it's too easy to accidentally dismiss the notification rather than triggering `application(application:, handleActionWithIdentifier:, forRemoteNotification:, withResponseInfo: , completionHandler:` 
If the notification is accidentally closed, the user has lost all of his inputted text and there is no way to recover it... it's a waste of time for the user + the user will believe that it has worked properly. This is really the biggest issue here... I discovered this the hard way. It's essentially a false positive. 

**Solution**
Increase the the size of the "send" button so that tapping anywhere near the "send" text will trigger the expected chain of events rather than closing the notification.

**Comment by kunass2** [comment]
Ok, I do it and release solution along with the next version. Thank you for response.

**Comment by camclendenin** [comment]
Great, thanks @kunass2

**Comment by kunass2** [comment]
@camclendenin  I just released a new version with much bigger send button.
